### PR TITLE
QR Code Widget

### PR DESCRIPTION
**Pull request by jperon**
Generates a QR code from a selected column.

### CODE REVIEW

**Comment by jperon** [comment]
I’ve just pushed a modification that allows to define a list of strings in order to get several QR codes. It’s backward-compatible: if a string is defined, it will get encoded just as before.

**Comment by jperon** [comment]
Given the excellent change coming from https://github.com/gristlabs/grist-core/commit/1dafe4bae0791eb60714fc0069180c62039ee16c, I’ve added the ability to resize the QR code on widow resize.

**Comment by paulfitz** [comment]
@berhalak are you still interested in reviewing this widget?

**Review by berhalak — APPROVED** [review]
Hi @jperon,

I totally forgot to merge this pull request, so sorry about that. It works and looks very good, thank you.

**Comment by jperon** [comment]
Thank *you* for all the hard work!

**Pull request merged**
