### PR TITLE
New widget - Notepad - rich text editor.

### PR DESCRIPTION
**Pull request by berhalak**
New widget: "Notepad". 'WYSIWYG'-like editor similar to Markdown with autosave and images.

### CODE REVIEW

**Comment by berhalak** [comment]
I discussed this with Natalie and we decided that it would be useful to add it for Thursday's webinar.

**Comment by paulfitz** [comment]
Cute! Nice to have a way to include images. Encoding them in the cell may give @dsagal qualms about data engine performance, but it seems fine for small-scale use-cases. I played around with the widget, and moving from row to row felt a bit hit and miss, but I think it was because I had some material in the column to be edited that was not in "{ops: ..." serialization format. Would it be possible to "upgrade" such material?

**Comment by anaisconce** [comment]
Looks great! I'm having fun with it and eager to have it!

**Review by paulfitz — APPROVED** [review]
Thanks @berhalak !

**Pull request merged**
